config/routes.rb
Rails.application.routes.draw do
  resources :enumerations
  resources :users
  root 'users#index'

end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :user
  #self.inheritance_column = :race
end

app/models/email_type.rb
class EmailType  < Enumeration



end

app/models/enumeration.rb
class Enumeration < ActiveRecord::Base

end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :user
end

app/models/phone_type.rb
class PhoneType <Enumeration

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :emails
  has_many :phones
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :emails, reject_if: :all_blank, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/enumerations_controller.rb
class EnumerationsController < ApplicationController
  before_action :set_enumeration, only: [:show, :edit, :update, :destroy]

  # GET /enumerations
  # GET /enumerations.json
  def index
    @enumerations = Enumeration.all
    EmailType
    PhoneType
  end

  # GET /enumerations/1
  # GET /enumerations/1.json
  def show
  end

  # GET /enumerations/new
  def new
    @enumeration = Enumeration.new
  end

  # GET /enumerations/1/edit
  def edit
  end

  # POST /enumerations
  # POST /enumerations.json
  def create
    @enumeration = Enumeration.new(enumeration_params)

    respond_to do |format|
      if @enumeration.save
        format.html { redirect_to @enumeration, notice: 'Enumeration was successfully created.' }
        format.json { render :show, status: :created, location: @enumeration }
      else
        format.html { render :new }
        format.json { render json: @enumeration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enumerations/1
  # PATCH/PUT /enumerations/1.json
  def update
    respond_to do |format|
      if @enumeration.update(enumeration_params)
        format.html { redirect_to @enumeration, notice: 'Enumeration was successfully updated.' }
        format.json { render :show, status: :ok, location: @enumeration }
      else
        format.html { render :edit }
        format.json { render json: @enumeration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enumerations/1
  # DELETE /enumerations/1.json
  def destroy
    @enumeration.destroy
    respond_to do |format|
      format.html { redirect_to enumerations_url, notice: 'Enumeration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enumeration
      @enumeration = Enumeration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enumeration_params
      params.require(:enumeration).permit(:name, :type)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enumerations_helper.rb
module EnumerationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/enumerations/_form.html.slim
= simple_form_for(@enumeration) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :type

  .form-actions
    = f.button :submit

app/views/enumerations/edit.html.slim
h1 Editing enumeration

== render 'form'

= link_to 'Show', @enumeration
'|
= link_to 'Back', enumerations_path

app/views/enumerations/index.html.slim
h1 Listing enumerations

table
  thead
    tr
      th Name
      th Type
      th
      th
      th

  tbody
    - @enumerations.each do |enumeration|
      tr
        td = enumeration.name
        td = enumeration.type
        td = link_to 'Show', enumeration
        td = link_to 'Edit', edit_enumeration_path(enumeration)
        td = link_to 'Destroy', enumeration, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Enumeration', new_enumeration_path

app/views/enumerations/new.html.slim
h1 New enumeration

== render 'form'

= link_to 'Back', enumerations_path

app/views/enumerations/show.html.slim
p#notice = notice

p
  strong Name:
  = @enumeration.name
p
  strong Type:
  = @enumeration.type

= link_to 'Edit', edit_enumeration_path(@enumeration)
'|
= link_to 'Back', enumerations_path

app/views/layouts/application.html.slim
html
head
  title StiBasic
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

body
  .container-fluid
    = yield

app/views/users/_email_fields.html.slim
.nested-fields
  = f.input :email_type_id,:collection => EmailType.all,:label_method => :name,:value_method => :id,:label => 'Email' ,:include_blank => false
  = f.text_field :email
  = link_to_remove_association 'Remove Task', f, class: 'btn btn-default'

app/views/users/_form.html.slim
= simple_form_for(@user)  do |f|
  = f.error_notification

  .form-inputs
    =f.input :name

  #emails
    = f.fields_for :emails do |e|
      = render 'email_fields', f: e
    = f.fields_for :phones do |p|
      = render 'phone_fields', f: p
    .links
      = link_to_add_association 'add email', f, :emails, class: "btn btn-default"
      = link_to_add_association 'add phone', f, :phones, class: "btn btn-default"

  .form-actions
    .links
      /= link_to_add_association 'add email', f, :emails, class: "btn btn-default"
      /= link_to_add_association 'add phone', f, :phones, class: "btn btn-default"
    = f.button :submit

app/views/users/_phone_fields.html.slim
.nested-fields
  = f.input :phone_type_id,:collection => PhoneType.all,label_method: :name,value_method: :id,label: 'Phone' ,:include_blank => false
  = f.text_field :phone
  = link_to_remove_association 'Remove', f, class: 'btn btn-default'

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
.row
  .col-md-8
    h1 Listing users

    table
      thead
        tr
          th
          th
          th

      tbody
        - @users.each do |user|
          tr
            td = link_to 'Show', user
            td = link_to 'Edit', edit_user_path(user)
            td = link_to 'Destroy', user, data: {:confirm => 'Are you sure?'}, :method => :delete

    br

    = link_to 'New User', new_user_path

app/views/users/new.html.slim
.row
  .col-md-6.centre
    h1 New user

    == render 'form'

    = link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice


= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path